id: P006965
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5441
  title: ངེས་སྒྲོན་རྣམ་བཤད།
  author: ''
  volumes:
    bbd4aca2a0fc4a1893c8a592213347e8:
      image_group_id: I3CN5443
      title: ''
      volume_number: 1
      total_pages: 316
ebook_metadata:
  title: ངེས་སྒྲོན་རྣམ་བཤད།
  author: ''
  sku: P006965
  cover: cover.jpg
  layers:
  - pagination
