id: P006965
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5441
  title: ངེས་སྒྲོན་རྣམ་བཤད།
  author: ''
  volumes:
    db89f7f7d5e44f6085c19c9d71fc1987:
      image_group_id: I3CN5443
      title: Volume 1 of nges shes rin po che'i sgron me rtsa 'grel/
      volume_number: 1
      total_pages: 316
      base_file: v001.txt
